### ISSUE TITLE
Table 'tc_dev.Roles' doesn't exist (SQL: select * from `Roles`)

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#102]
When you go to the users list and select a user it ill display the error.

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tc_dev.Roles' doesn't exist (SQL: select * from `Roles`)
```

**Comment by ghermans** [comment]
@Tjoosten this one is fixed the issue was a typo in the model.

**Comment by ghermans** [comment]
@Tjoosten ?

**Comment by Tjoosten** [comment]
do you have a route?

**Comment by ghermans** [comment]
/staff/policies

**Comment by Tjoosten** [comment]
@ghermans ill check tomorrow

**Comment by Tjoosten** [comment]
@ghermans erroro does not occur on my installation. Can u confirm for your installation. If no error plz close this

**Comment by ghermans** [comment]
This has been fixed.
