### ISSUE TITLE
Create task requests

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#116]
For example if an employee needs to call a customer back when there is a high inbound traffic, it is wisely to manage outbound calls with a "priority" system.

for example employee selects outbound call -> next dropdown(Outbound sales - user got disconnected, etc) on those values we link priority numbers so managers know what is urgent and what can wait.
- [x] List all tasks in a table. 
- [x] Add requester relation.
- [x] Assignee relation
- [x] Create form to request tasks. 
- [x] Debug insert method. 
- [x] Allow managers to edit tasks 
- [x] Add edit button to view
- [x] Add edit modal.
- [x] Add edit method.
- [x] Create search method.

**Comment by Tjoosten** [comment]
But the task controller is filled in?

**Comment by Tjoosten** [comment]
@ghermans Can u make the views. I will do all the logic.

**Comment by ghermans** [comment]
I will add them tonight
