### ISSUE TITLE
Departments

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#123]
### Create a new department
- [X] Create a form to insert the data
  
  **Requested fields for this**:
- department_name
- department_manager
- department_description
### Edit department
- [x] Create a tab navigation 
  
  **Links for this**:
- [x] General
- [x] Teams
- [x] Notification settings
- [x] Custom Dashboard

**Comment by ghermans** [comment]
@Tjoosten i will add the tab page for the edit view tonight.

**Comment by Tjoosten** [comment]
@ghermans URI?

**Comment by ghermans** [comment]
staff/departments/edit

**Comment by Tjoosten** [comment]
@ghermans can u edit the views for this?
