### ISSUE TITLE
Syntax error. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#129]
On update a task. 
<img width="1186" alt="schermafbeelding 2016-03-30 om 19 04 21" src="https://cloud.githubusercontent.com/assets/5157609/14150631/493627bc-f6aa-11e5-91ea-8ce13da1a86d.png">

**Comment by ghermans** [comment]
For the current moment this is normal, i only created the views without any other features.

**Comment by Tjoosten** [comment]
@ghermans any update?

**Comment by ghermans** [comment]
@Tjoosten i'm waiting for your commits on #100  and #176  before i can finish the task controller.
Since the takscontroller will make use of them, for example to send notifications to managers.
