### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#130]
<img width="660" alt="schermafbeelding 2016-03-30 om 19 18 26" src="https://cloud.githubusercontent.com/assets/5157609/14151030/3f7cb5fe-f6ac-11e5-8508-8ef95c246837.png">

**Comment by ghermans** [comment]
I guess this is some leftover from the spatie/permission package.

**Comment by Tjoosten** [comment]
I'll fix it then

**Comment by Tjoosten** [comment]
@ghermans UPDATE: its not clear to me what this functions do.
