### ISSUE TITLE
Dynamic task types

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#132]
- [x] Add link to the sidebar
- [x] Save the task types in the database.
- [x] Add the possibility to remove the type.
- [x] Change the vars in the view file @Tjoosten 
- [ ] Add form validation when creating a new type. 
- [x] Output the priority name and not the id.

**db fields**
name,
priority

![selection_150](https://cloud.githubusercontent.com/assets/1594411/14165326/198af7dc-f708-11e5-8ab5-75bbf53b4f70.png)

**Comment by Tjoosten** [comment]
Like in the sentence off create a database table and a seeder? @ghermans

**Comment by ghermans** [comment]
the data will be insert true a form. since task types are not the same in each company. however for example "Callback" would be a task type that any company could use, so maybe we can use a "Generate tasks" button that fills the DB with some predefined types?

**Comment by Tjoosten** [comment]
@ghermans table migration added. can u make a hyperlink in the sidebar. I like to make the functions and controllers.

**Comment by ghermans** [comment]
@Tjoosten i have updated the task list.

**Comment by Tjoosten** [comment]
The priority is a id???

**Comment by Tjoosten** [comment]
5ab9b42f20a07c5e7a3fbbabf5b7fdd62fb0871b @ghermans needs a look.

**Comment by Tjoosten** [comment]
@ghermans What fields need validation?

**Comment by ghermans** [comment]
name, priority

**Comment by Tjoosten** [comment]
why on priority when low is standard?

**Comment by ghermans** [comment]
indeed only name

**Comment by Tjoosten** [comment]
@ghermans validation added if no new points this issue can be closed.

**Comment by ghermans** [comment]
When i try to add a new type i get a blank page with the text: Forbidden

**Comment by Tjoosten** [comment]
Should be fixed now

**Comment by Tjoosten** [comment]
@ghermans can u check it?

**Comment by Tjoosten** [comment]
@ghermans validation has been added so this can be closed.
