### ISSUE TITLE
Route points to a dark hole.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#139]
```
Route::get('staff/permissions/edit/{id}', 'StaffController@edit_permission')->name('staff.permissions.edit');
```

@ghermans  Staff controller doesn't have that function

**Comment by ghermans** [comment]
The function has been added

Todo 
- [ ] Add form validation
- [ ]  Save the values to the database after updating the form.

**Comment by ghermans** [comment]
@Tjoosten task list has been updated

**Comment by Tjoosten** [comment]
@ghermans where is the PR?

**Comment by Tjoosten** [comment]
@ghermans can this be closed or not?

**Comment by ghermans** [comment]
@Tjoosten yes however the update function still needs to be written related to #100
