### ISSUE TITLE
Assign menu links to roles

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#141]
The menu sections should be based on the roles so it can verify if a user has access to that part of the application.

For example the Staff section should only be available for administrators,managers but not for normal staff people.
Maybe this can be integrated in a view so admins can dynamically modify the roles for menus in the Roles controller.

**Comment by Tjoosten** [comment]
<img width="1127" alt="schermafbeelding 2016-04-29 om 00 00 39" src="https://cloud.githubusercontent.com/assets/5157609/14902828/99749880-0d9d-11e6-8ae8-f392ef1e986e.png">

I see implementation parts for this in the source code. @ghermans can u confirm this has be doen or done. If not can u update the issue description?

**Comment by ghermans** [comment]
This still needs to be done, the code you put here is just for adding the active class on the links

**Comment by Tjoosten** [comment]
<img width="814" alt="schermafbeelding 2016-04-29 om 00 11 00" src="https://cloud.githubusercontent.com/assets/5157609/14903064/e1824ab8-0d9e-11e6-8faa-878d7c0e7fb2.png">

as you see here above this chunk of code there stand something for the ACL

**Comment by ghermans** [comment]
indeed, my bad, however it needs some modifications, i will update the description during this night.

**Comment by Tjoosten** [comment]
@ghermans any update. If it is ok we can close this one

**Comment by ghermans** [comment]
@Tjoosten  the update:

for the current moment we manually add    @if(Auth::user()->('Administrator')
I guess the best way is to set this dynamic instead static

What i suggest is to create  2 models 
- [ ] SidebarGroups
  Here we add the name for the group for example Settings
- [ ] SidebarLinks
  Here we add the name & url that is assigned to the sidebargroup for example Basic settings, backup etc

**Comment by Tjoosten** [comment]
@ghermans maybe for a next release?

**Comment by Tjoosten** [comment]
CLOSED DUE INACTIVITY
