### ISSUE TITLE
Replace the plugins cdn with local files

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#143]
For the current moment we are loading a lot of jquery & css plugins from a CDN.
To reduce the load time i think it will be better to run the plugins local instead true CDN.

**UPDATE**
- [ ]  A couple of files still needed to be set local 
- [ ]  @tjoosten needs to active cache busting on the files.
- [ ] @ghermans will fix the font issue.

**Comment by Tjoosten** [comment]
i think CDN's are faster. But maybe we should test this one first?
