### ISSUE TITLE
Unused function.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#144]
<img width="714" alt="schermafbeelding 2016-04-01 om 15 52 56" src="https://cloud.githubusercontent.com/assets/5157609/14208876/e038b9b8-f821-11e5-98f3-948c6001cc84.png">

@ghermans can i check if we can delete this function or not?

**Comment by ghermans** [comment]
This one is used when you update staff/edit/id

**Comment by Tjoosten** [comment]
@ghermans Alright i'll close this issue then.
