### ISSUE TITLE
Set backup method.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#145]
I could be handy that we also provide a backup system for timecontrol. 

@ghermans If you want i will implement this one. 

NEEDS: 
- config the mailing user
- config the schedular. 
- document.

**Comment by Tjoosten** [comment]
@ghermans can u tell me what is the config var from the platform administrator or developer.

If you want i beam u up on skype. if you want

**Comment by ghermans** [comment]
@Tjoosten config(timecontrol.email)

**Comment by Tjoosten** [comment]
Fixed later in the evening
