### ISSUE TITLE
Fix font issue in the sidebar

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#158]

**Comment by ghermans** [comment]
@Tjoosten i found that when you use the bootstrap CDN there is no issue.
When you load the bootstrap.css local the font fails.

**Comment by Tjoosten** [comment]
@ghermans that's odd. Maybe we need to report a issue on the original bootstrap repo

**Comment by Tjoosten** [comment]
@ghermans can we close this issue also?

**Comment by ghermans** [comment]
Yes
