### ISSUE TITLE
Integrate Jquery-stepy for form-wizard

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#163]

**Comment by ghermans** [comment]
PR almost ready.

![selection_159](https://cloud.githubusercontent.com/assets/1594411/14234957/5abc6fe8-f9f0-11e5-97f1-7d2734d2a03f.png)

**Comment by Tjoosten** [comment]
@ghermans validation needs to be inserted

**Comment by ghermans** [comment]
@Tjoosten i have added basic validation in the wizard with jquery.
The laravel validation still needs to be added

**Comment by Tjoosten** [comment]
@ghermans Alright padawan

**Comment by Tjoosten** [comment]
@ghermans Workload update plz

**Comment by ghermans** [comment]
Nothing changed since my last reply.
