### ISSUE TITLE
Implement codecov

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#168]

**Comment by Tjoosten** [comment]
@ghermans I think it's cleaner to use scrutinizer for this. Srry for the extra unused workload i delivered.

**Comment by Tjoosten** [comment]
@ghermans status needed. If not important. I think we need to close this one.

**Comment by ghermans** [comment]
For some reason the codecov is giving timeouts in scrutinizer , i will take a look at it when i have the time.

**Comment by Tjoosten** [comment]
@ghermans alright

**Comment by Tjoosten** [comment]
closed for now
