### ISSUE TITLE
Odd looking view. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#173]
<img width="893" alt="schermafbeelding 2016-04-05 om 10 11 28" src="https://cloud.githubusercontent.com/assets/5157609/14275306/d25773f0-fb16-11e5-8bb7-91c307b1eede.png">

Bug appears to come from: 

``` html
<div id="piechart" style="width: 700px; height: 400px;"></div>
```

We need to code this do percents.

**Comment by ghermans** [comment]
@Tjoosten I don't get the same result here

![selection_161](https://cloud.githubusercontent.com/assets/1594411/14281017/d057e9ca-fb36-11e5-9bc5-d5ca45447dcf.png)

**Comment by Tjoosten** [comment]
And on smaller screen size?

**Comment by ghermans** [comment]
I guess this is because of the hard coded style.

    <div id="piechart" style="width: 700px; height: 400px;"></div>
