### ISSUE TITLE
Dynamic color setup for timetable & labels

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#180]
- [x] Add migration file
- [x] Add a color picker to   `views/tasks/manage_types.blade.php`

**Comment by Tjoosten** [comment]
@ghermans same migration as in voicetank? If not can u give me the db scheme's so i can write the migration?

**Comment by ghermans** [comment]
@Tjoosten indeed same as voicetank

**Comment by Tjoosten** [comment]
Alright later in the evening i will bring up the migration file.

**Comment by ghermans** [comment]
@Tjoosten description has been updated.

**Comment by Tjoosten** [comment]
@ghermans having issue with the js implementation. I will push it can u take a look?
