### ISSUE TITLE
Create permission schema for the docs. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#188]
We need to write out the permission schema for Timecontrol. Because this can be handy in the documentation so people can reference to it. When they have questions about permissions.

**Comment by ghermans** [comment]
I have started with the scheme https://timecontrol.readme.io/docs/permission-scheme

**Comment by Tjoosten** [comment]
<img width="760" alt="schermafbeelding 2016-04-29 om 12 44 07" src="https://cloud.githubusercontent.com/assets/5157609/14914151/1f44150c-0e08-11e6-9c3b-42c4856fd6fa.png">
Typo found

**Comment by Tjoosten** [comment]
@ghermans can u fix the typo and close this issue

**Comment by Tjoosten** [comment]
typo fixed
