### ISSUE TITLE
NL translation

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#19]
# Description

All language files need to be translated to dutch.
The translation files can be found in resources/lang/nl

**Comment by Tjoosten** [comment]
Will add the standard translation files. The occasional translation file. Can be added in a later release. Decision made because inactivity on the issue. After the file will be added. I will close the issue

**Comment by ghermans** [comment]
This stays open until it is finished.

**Comment by ghermans** [comment]
Sorry since the commit was not tagged i didn't noticed that this was finished.
