### ISSUE TITLE
Add basic authentication

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#2]
- [x] Add Authentication
- [x] Add ACL

**Comment by Tjoosten** [comment]
?

**Comment by ghermans** [comment]
For the current moment users can be added to the system.
Todo assign roles to user.

**Comment by Tjoosten** [comment]
Nice!

**Comment by ghermans** [comment]
![edit_user](https://cloud.githubusercontent.com/assets/1594411/11758936/a86783f0-a071-11e5-908d-68c0e25deb2d.png)

**Comment by Tjoosten** [comment]
ok

**Comment by ghermans** [comment]
#24 Needs to be fixed before we continue on this.

**Comment by ghermans** [comment]
- The last bug regarding the user model has been fixed.
- For now the edit_user page needs to be fixed so that the user type is correctly selected.
  ![selection_097](https://cloud.githubusercontent.com/assets/1594411/12773053/15ac8484-ca38-11e5-91e1-7b408f3896b8.png)

**Comment by ghermans** [comment]
Waiting on #52, @Tjoosten status update?

**Comment by ghermans** [comment]
After the bouncer integration the menu items are not displayed.

![selection_1323](https://cloud.githubusercontent.com/assets/1594411/13559110/19be6ece-e410-11e5-9b29-4ed677bd116f.png)

**Comment by Tjoosten** [comment]
@ghermans Status update on this plz!

**Comment by ghermans** [comment]
@Tjoosten this still needs to be done:
- [ ] Add new roles and assign permissions.
- [ ] Add new permissions from staff/permissions
- [ ] Assign role to user
- [ ] Add a protection that only admins can remove admins in the destroy function in staffcontroller.

**Comment by Tjoosten** [comment]
I close this one because i got further in #100
