### ISSUE TITLE
FR translation

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#20]
# Description

All language files need to be translated to dutch.
The translation files can be found in resources/lang/fr

**Comment by Tjoosten** [comment]
Will add the standard translation files. The occasional translation file. Can be added in a later release. Decision made because inactivity on the issue. After the file will be added. I will close the issue

**Comment by ghermans** [comment]
@tlarbalestrier will update the FR translations.

**Comment by Tjoosten** [comment]
@ghermans around what time?

**Comment by ghermans** [comment]
@Tjoosten not today :p

**Comment by ghermans** [comment]
@Tjoosten it is scheduled for next weekend.

**Comment by Tjoosten** [comment]
@ghermans Status update

**Comment by ghermans** [comment]
@Tjoosten @tlarbalestrier since this always gets rescheduled i made the decision to not support FR by default.
