### ISSUE TITLE
Breaktool relationships

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#215]
## Relationships for breaktool migrations #214

**Affected models:** **User**, Departments, Break

| Type | function | name |
| --- | --- | --- |
| Users | Many to many | BreakQueue |
| Users | Many to many | Break |

**Comment by ghermans** [comment]
@Tjoosten feel free to modify.

**Comment by Tjoosten** [comment]
in what models the need?

**Comment by ghermans** [comment]
User, Departments, Break*
