### ISSUE TITLE
Protect admin users

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#23]
We should insert a protection for admin roles so other users can't delete them.

**Comment by Tjoosten** [comment]
refer to #52

**Comment by Tjoosten** [comment]
@ghermans can you give me a overview off the admin routes?

**Comment by Tjoosten** [comment]
@ghermans ?

**Comment by ghermans** [comment]
@Tjoosten check slack :)

**Comment by Tjoosten** [comment]
@ghermans I see nothing about the routes

**Comment by ghermans** [comment]
I guess you refer to this?

```
Route::get('staff/remove/{id}', 'StaffController@destroy')->name('staff.destroy');
```

**Comment by Tjoosten** [comment]
Alright  il fix it tris evening/night

**Comment by Tjoosten** [comment]
@ghermans  What needs to be still done on this?

**Comment by Tjoosten** [comment]
@ghermans update plz

**Comment by Tjoosten** [comment]
Closed due inactivity
