### ISSUE TITLE
Vacation management

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#233]
## Description

Users can request vacation this can be different types like payed holiday,  reduction in working days, overtime
## Todo
- [x]  Create a new controller
- [x] Add vacation delete method. 
- [x] Role implementation  
- [x] Create views

**Comment by Tjoosten** [comment]
| Value | Type |
| --- | --- |
| user_id | integer |
| department_id | integer |
| type | integer |
| from | datetime |
| until | datetime |
| status | integer |

**Comment by Tjoosten** [comment]
@ghermans can u post a feature description. above the todo list

**Comment by ghermans** [comment]
@Tjoosten done

**Comment by Tjoosten** [comment]
I'm taking this over for now.

**Comment by Tjoosten** [comment]
@ghermans need role overview for the role implementation.

**Comment by ghermans** [comment]
@Tjoosten  users can request vacation , show a list with all their requests
Managers can request/manage the requests.
