### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#28]
# Description

We need a website for time control
# Platform

Choose between Laravel or Joomla.
# Pages
- [ ] Features
- [ ] Pricing
- [ ] Support:
  - [ ] Documentation
  - [ ] Knowledge base
  - [x] Forum
- [ ] Contact

**Comment by Tjoosten** [comment]
I vote for Laravel!

**Comment by Tjoosten** [comment]
Is there a repo for this? If not where i can find the source? So i can also work on it.

**Comment by Tjoosten** [comment]
@ghermans ?

**Comment by ghermans** [comment]
There was no repo for this. i have just created a new repo for this where you can store commits idevelopment/timecontrol.be.

**Comment by Tjoosten** [comment]
There is a seperate repo for this so i close this one
