### ISSUE TITLE
Add phpunit tests

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#51]

**Comment by ghermans** [comment]
:+1:

**Comment by Tjoosten** [comment]
PR #85

**Comment by Tjoosten** [comment]
Add php is set I create a new issue. Because the tests are broken

**Comment by Tjoosten** [comment]
I will create a seperate branch for it

**Comment by Tjoosten** [comment]
@ghermans still some test needs to be written

**Comment by Tjoosten** [comment]
@ghermans Added for almost everything tests. I close this one. if new tests needed plz open a new issue
