### ISSUE TITLE
Replace spatie/permission with bouncer

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#52]
@Tjoosten would you mind doing this?

**Comment by Tjoosten** [comment]
if you can throw me an overview of the roles, and what needs to be where, etc.

**Comment by ghermans** [comment]
@Tjoosten the default roles are (admin, agent, manager), however there should be a possibility that administrations can create a new role.

**Comment by ghermans** [comment]
https://github.com/idevelopment/timecontrol/tree/development/resources/views/staff
