### ISSUE TITLE
Add grumPHP

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#56]

**Comment by ghermans** [comment]
@Tjoosten can you update the package.json for this?

**Comment by Tjoosten** [comment]
Package.json?

**Comment by ghermans** [comment]
Well i had issues with running grumphp because grunt was not installed on my system. so maybe grunt can be set in the package file?

**Comment by Tjoosten** [comment]
Nha its laravel standard with gulp? So why grunt?

**Comment by ghermans** [comment]
method to replicate the issue 
- Clone the development branch
- try to push a commit.

It will output an error.

**Comment by Tjoosten** [comment]
Do you have a actual output?

**Comment by ghermans** [comment]
It first failed on the running task Grunt.

GrumPHP is sniffing your code!
Running task  1/12: Behat
Running task  2/12: Codeception
Running task  3/12: Composer
Running task  4/12: Blacklist
Running task  5/12: Grunt

i updated my fork and things look good so will close this issue.

**Comment by Tjoosten** [comment]
?

**Comment by ghermans** [comment]
@Tjoosten issue is fixed

**Comment by Tjoosten** [comment]
Alright
