### ISSUE TITLE
Departments model is missing relation for manager

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#71]
For the current moment the userid is displayed instead of the realname.

![selection_129](https://cloud.githubusercontent.com/assets/1594411/13535963/5ee389be-e23d-11e5-9f03-fd25505c1836.png)

**Comment by Tjoosten** [comment]
What relation type u wish off this?

**Comment by ghermans** [comment]
@Tjoosten "Many To Many" relationship will be the best one for this i guess.

**Comment by Tjoosten** [comment]
@ghermans can u write this? Becaise it's driving me nuts atm

**Comment by ghermans** [comment]
@Tjoosten what is the issue that you have with this one?

**Comment by ghermans** [comment]
@Tjoosten the "store" function should be fixed, can you please verify?

**Comment by Tjoosten** [comment]
@ghermans i will verify it tomorrow if not verified in the evening fire my ass at slack plz

**Comment by ghermans** [comment]
@Tjoosten i have my gloves and lubricant ready ;)

**Comment by ghermans** [comment]
@Tjoosten can you provide any update regarding this one?

**Comment by Tjoosten** [comment]
I'm just started to look for it

**Comment by ghermans** [comment]
Related to #123

**Comment by ghermans** [comment]
@Tjoosten  can you provide any update regarding this one?

**Comment by Tjoosten** [comment]
@ghermans seems like its fixed
